---
- hosts: all
  sudo: yes
  vars:
    ruby_version: 1.9.3
    user: vagrant
  tasks:
    - name: Update Apt cache
      apt: update_cache=yes

    - name: Install dependencies
      apt: pkg={{ item }} state=installed
      with_items:
        - libmysqlclient-dev
        - mysql-server
        - git
        - curl

    # RVM script will issue and error code despite a successful install, hence the suppression of errors.
    - name: Ruby | Install RVM (and suppress fail)
      shell: curl -L https://get.rvm.io | bash -s stable --quiet-curl --auto-dotfiles --ruby={{ ruby_version }} creates=/home/{{ user }}/.rvm
    #  ignore_errors: true
    
    - name: Ruby | Add RVM to bash profile
      lineinfile:
        dest=/home/{{ user }}/.bashrc
        state=present
        line='[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"'

#     - name: Install ruby1.9.3
#       apt: pkg=ruby1.9.3 state=present
# 
#     - name: Install ruby1.9.1-dev
#       apt: pkg=ruby1.9.1-dev state=present
# 
#     - name: Install rubygems
#       apt: pkg=rubygems state=present

#     - name: Install rake
#       gem: name=rake state=latest
# 
#     - name: Install bundle
#       gem: name=rake state=latest

    - name: Clone Huginn
      git: repo=git://github.com/cantino/huginn.git dest=/home/vagrant/huginn update=no
