---
- hosts: all
  vars:
    ruby_version: 1.9.3
    user: vagrant
  tasks:
    - name: Update Apt cache
      apt: update_cache=yes
      sudo: true

    - name: Install dependencies
      apt: pkg={{ item }} state=installed
      sudo: true
      with_items:
        - libmysqlclient-dev
        - mysql-server
        - git
        - curl

    # RVM script will issue and error code despite a successful install, hence the suppression of errors.
    - name: Ruby | Install RVM (and suppress fail)
      shell: curl -L https://get.rvm.io | bash -s stable --quiet-curl --auto-dotfiles --ruby={{ ruby_version }} creates=/home/{{ user }}/.rvm
    #  ignore_errors: true
    
    - name: Ruby | Add RVM to bash profile
      lineinfile:
        dest=/home/{{ user }}/.bashrc
        state=present
        line='[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"'

    - name: Clone Huginn
      git: repo=git://github.com/cantino/huginn.git dest=/home/vagrant/huginn update=no

    - name: Ruby | Gem install rake & bundle
      shell: PATH=$PATH:/home/{{ user }}/.rvm/bin && rvm default@huginn --create do gem install rake bundle chdir=/home/vagrant/huginn

    # - name: Ruby | Run bundle
    #   shell: PATH=$PATH:/home/{{ user }}/.rvm/bin && rvm default@huginn --create do bundle chdir=/home/vagrant/huginn

    # Log into the guest machine (using "vagrant ssh") and run the following commands:
    #
    #     $ cd huginn/
    #     $ bundle
    #     $ git remote add upstream https://github.com/cantino/huginn.git
    #     $ sed -e "s/REPLACE_ME_NOW\!/$(rake secret)/g" .env.example > .env
    #     $ rake db:create && rake db:migrate && rake db:seed && foreman start
