---
- hosts: all
  vars:
    ruby_version: 1.9.3
    user: vagrant
  tasks:
    - name: Update Apt cache
      apt: update_cache=yes
      sudo: true

    - name: Install dependencies
      apt: pkg={{ item }} state=installed
      sudo: true
      with_items:
        - libmysqlclient-dev
        - mysql-server
        - git
        - curl

    # RVM script will issue and error code despite a successful install, hence the suppression of errors.
    - name: Ruby | Install RVM (and suppress fail)
      shell: curl -L https://get.rvm.io | bash -s stable --quiet-curl --auto-dotfiles --ruby={{ ruby_version }} creates=/home/{{ user }}/.rvm
    #  ignore_errors: true
    
    - name: Ruby | Add RVM to bash profile
      lineinfile:
        dest=/home/{{ user }}/.bashrc
        state=present
        line='[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"'

    - name: Clone Huginn
      git: repo=git://github.com/cantino/huginn.git dest=/home/vagrant/huginn update=no

    - name: Ruby | Gem install rake & bundle
      shell: PATH=$PATH:/home/{{ user }}/.rvm/bin && rvm default@huginn --create do gem install rake bundle
